	INSERT INTO bears (
    name,
    age,
    gender,
    color,
    temperament,
    alive
  )
  VALUES
      (
          "Mr. Chocolate",
          2,
          "M",
          "brown",
          "playful",
          1
      ),
      (
          "Rowdy",
          24,
          "M",
          "black/brown",
          "feisty",
          1
      ),(
          "Tabitha",
          6,
          "F",
          "brown",
          "easy",
          1
      ),
      (
          "Seargeant Brown",
          8,
          "M",
          "black",
          "domineering",
          1
      ),
      (
          "Melissa",
          2,
          "F",
          "brown/black",
          "shy",
          1
      ),
      (
          "Grinch",
          1,
          "M",
          "brown",
          "cautious",
          1
      ),
      (
          "Wendy",
          1,
          "F",
          "brown",
          "playful",
          1
      ),
      (
          NULL,
          9,
          "F",
          "black",
          "aggressive",
          1
      );
